/**
 * View export (T060).
 *
 * The export exists so a saved projection can leave the app and still mean
 * something. That imposes one rule above all others: **the export is derived, not
 * authoritative.** Two things follow, and they shape this whole module.
 *
 *  - **Markdown is compiled from the canonical AST, never from cached source.**
 *    `ViewDTO.content` is the validated tree; the compiled Markdown and the
 *    Mermaid source are *display artefacts* that could be stale, hand-edited, or
 *    regenerated by a newer compiler. Re-reading a cached string would export
 *    whatever is in that column rather than what the tree says (T060-R01,
 *    docs/03_contracts/09 §4: 不能让手工修改源码绕过校验).
 *  - **The file carries today's date, not the model's.** Nothing here calls a
 *    model, so exporting twice produces byte-identical bytes apart from the export
 *    timestamp. That is what makes "compare the two files" a meaningful check
 *    (T060-C05) instead of a race.
 *
 * A third rule is about what is *absent*: there is no field in `ViewExport` for an
 * API key, an Authorization header, or a provider request body. The whitelist is
 * the type, so a future caller cannot leak one by spreading an object into it
 * (T060-R02, mirroring `runDiagnosticsExport.ts`).
 */
import { compileMindmap } from './compileMindmap';
import type { MindmapContent, ViewDTO } from './knowledge';
import { MINDMAP_COMPILER_VERSION } from './compileMindmap';

/** Bumped when the exported field set or its meaning changes. */
export const VIEW_EXPORT_SCHEMA_VERSION = 1;

/** The formats this build can actually produce (T060-R06: no PNG/PDF promises). */
export const VIEW_EXPORT_FORMATS = ['markdown', 'json'] as const;
export type ViewExportFormat = (typeof VIEW_EXPORT_FORMATS)[number];

export function isViewExportFormat(value: string): value is ViewExportFormat {
  return (VIEW_EXPORT_FORMATS as readonly string[]).includes(value);
}

/**
 * The machine-readable export.
 *
 * `content` is the canonical AST — the same object the validator accepted and the
 * renderer draws — so a consumer can rebuild the view without this application.
 * `sourceSnapshot` carries the item/relation versions the view was built from,
 * which is what makes an imported copy able to say "this was based on revision 3"
 * rather than being silently unverifiable.
 */
export interface ViewExport {
  application: 'feini-brain';
  schemaVersion: number;
  kind: 'mindmap';
  viewId: string;
  name: string;
  /**
   * When the *content* was generated. Null for a view that was never generated by
   * a run, and never replaced by the export time — the two mean different things.
   */
  generatedAt: string | null;
  /** When this file was produced. The only field that differs between two exports. */
  exportedAt: string;
  /** The compiler that produced the Markdown in this export. */
  compilerVersion: string;
  promptVersion: string | null;
  contentHash: string | null;
  content: MindmapContent;
  sourceSnapshot: ViewDTO['sourceSnapshot'];
  /**
   * The freshness verdict at export time.
   *
   * Exported rather than left to the reader because the reader may not have this
   * application: a Markdown file opened in an editor must still say that its
   * sources have moved on (T060-R05, T060-C04). Deliberately a *verdict* and not a
   * re-export of live titles — the export must not grow into a mirror of the
   * knowledge base.
   */
  freshness: {
    isStale: boolean;
    changedItemCount: number;
    changedRelationCount: number;
    missingSourceCount: number;
    /** Same sentence the on-screen banner shows, or null when nothing changed. */
    reason: string | null;
  };
}

export interface BuildViewExportInput {
  view: ViewDTO & { kind: 'mindmap' };
  exportedAt: string;
  freshness: ViewExport['freshness'];
}

export function buildViewExport(input: BuildViewExportInput): ViewExport {
  const { view } = input;
  return {
    application: 'feini-brain',
    schemaVersion: VIEW_EXPORT_SCHEMA_VERSION,
    kind: 'mindmap',
    viewId: view.id,
    name: view.name,
    generatedAt: view.generatedAt,
    exportedAt: input.exportedAt,
    compilerVersion: MINDMAP_COMPILER_VERSION,
    promptVersion: view.promptVersion,
    contentHash: view.contentHash,
    content: view.content,
    sourceSnapshot: view.sourceSnapshot,
    freshness: input.freshness,
  };
}

/**
 * The Markdown the user actually reads.
 *
 * Structure: the compiled tree, then a provenance block. The block is *below* the
 * content rather than above it so the file reads as a document first and a receipt
 * second — but it is always emitted, because a Markdown file with no provenance is
 * indistinguishable from a hand-written outline a week later.
 *
 * The compiled body comes from `compileMindmap`, which is the same writer whose
 * output the renderer draws. Compiling here rather than re-emitting the tree is
 * what keeps "what you see" and "what you exported" the same document
 * (docs/03_contracts/09 §4).
 */
export function buildViewMarkdown(input: BuildViewExportInput): string {
  const exported = buildViewExport(input);
  const lines: string[] = [];

  lines.push(compileMindmap(exported.content));

  lines.push('', '---', '');
  lines.push('# 导出说明');
  lines.push('');
  lines.push(`- 视图名称：${exported.name}`);
  lines.push(`- 视图 ID：${exported.viewId}`);
  lines.push(
    `- 生成时间：${exported.generatedAt ?? '（没有生成记录）'}`,
  );
  lines.push(`- 导出时间：${exported.exportedAt}`);
  lines.push(`- 编译器版本：${exported.compilerVersion}`);
  if (exported.promptVersion) lines.push(`- 提示词版本：${exported.promptVersion}`);
  if (exported.contentHash) lines.push(`- 内容哈希：${exported.contentHash}`);

  // The freshness verdict is spelled out. A reader who opens this in an editor has
  // no other way to learn that the basis has moved (T060-R05: 不能把旧图标为最新整理).
  const { freshness } = exported;
  if (freshness.reason !== null || freshness.missingSourceCount > 0) {
    lines.push('', `> ⚠️ 依据可能已过期：${freshness.reason ?? `${freshness.missingSourceCount} 条来源已删除`}`);
    lines.push('> 这份导出反映的是**生成当时**的材料，不代表知识库的最新状态。');
  } else {
    lines.push('', '> 导出时来源版本与生成时一致。');
  }

  lines.push('', `## 来源清单（${exported.sourceSnapshot.items.length} 条）`, '');
  if (exported.sourceSnapshot.items.length === 0) {
    lines.push('（没有记录来源。）');
  } else {
    for (const item of exported.sourceSnapshot.items) {
      lines.push(`- ${item.id} 原文 v${item.rawVersion} · revision ${item.revision}`);
    }
  }
  if (exported.sourceSnapshot.relations.length > 0) {
    lines.push('', '## 参考的关系', '');
    for (const relation of exported.sourceSnapshot.relations) {
      lines.push(`- ${relation.id} revision ${relation.revision}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function buildViewExportJson(input: BuildViewExportInput): string {
  return `${JSON.stringify(buildViewExport(input), null, 2)}\n`;
}

/**
 * Build a download filename that cannot become a path.
 *
 * The contract is explicit that the name is built from the view id and a safe
 * date, and that an uncleaned title must never become part of a path
 * (docs/03_contracts/09 §6). This implementation goes one step further than
 * "strip separators": **the title is not used at all.**
 *
 * That is a deliberate choice, not an omission. Any title-derived name has to
 * survive its own sanitization rule, and every such rule is a bet that it caught
 * everything — encoding tricks, Unicode separators, reserved device names on
 * Windows (`CON`, `NUL`, `COM1`), trailing dots that Windows silently strips. A
 * name built only from a UUID and an ISO date has no such surface, and the
 * human-readable title is preserved inside the file, where it costs nothing.
 *
 * `name` is accepted so callers can pass it through honestly, and it is
 * intentionally unused; the signature documents that the parameter is not
 * trusted rather than leaving a reader to wonder whether it is.
 */
export function exportFileName(input: {
  format: ViewExportFormat;
  viewId: string;
  exportedAt: string;
}): string {
  const extension = input.format === 'markdown' ? 'md' : 'json';
  // Date only: two exports on the same day produce the same name, which is what
  // makes "download twice and compare" work without the browser renaming the file.
  const date = input.exportedAt.slice(0, 10);
  return `feini-mindmap-${input.viewId}-${date}.${extension}`;
}

/** The MIME type to serve each format with. */
export function exportContentType(format: ViewExportFormat): string {
  return format === 'markdown'
    ? 'text/markdown; charset=utf-8'
    : 'application/json; charset=utf-8';
}
